---
# --- Variables --- #

local :
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# --- Release Manager Config --- #

# Required: deployment targets
targets :
  - type : "bintray"
    user : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

# Required: packages to be deployed
packages :
  - repo : "snowplow-generic"
    name : "snowplow-stream-enrich"
    user_org : "snowplow"
    publish : true
    override : false
    continue_on_conflict : false
    version : <%= FUNC['sbt_version(3-enrich/stream-enrich/)'] %>
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>
    build_commands :
      - cd 3-enrich/stream-enrich && sbt assembly && cd ../..
    artifacts :
      - type : "zip"
        prefix : "snowplow_stream_enrich_"
        suffix : ""
        binary_paths :
          - "3-enrich/stream-enrich/target/scala-2.11/snowplow-stream-enrich-{{ packages.0.build_version }}.jar"
