---
# --- Variables --- #

local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# --- Release Manager Config --- #

# Required: deployment targets
targets:
  - type              : "awss3"
    access_key_id     : <%= ENV['AWS_ACCESS_KEY'] %>
    secret_access_key : <%= ENV['AWS_SECRET_KEY'] %>

# Required: packages to be deployed
packages:
  # AWS S3 plain upload example
  - name     : "spark-enrich-hosted-asset"        # Just for convenience
    bucket   : "snowplow-hosted-assets"
    path     : "3-enrich/spark-enrich"
    region   : "us-west-1"
    publish  : true
    override : false
    continue_on_conflict : false
    version  : <%= FUNC['sbt_version(3-enrich/spark-enrich/)'] %>

    # Required IF '--check-version' is passed: will assert that both versions are the same
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>

    # Optional: Build commands
    build_commands:
      - cd 3-enrich/scala-common-enrich/ && sbt +publishLocal && cd ../..
      - cd 3-enrich/spark-enrich && sbt assembly && cd ../..

    # Required: Artifact. Version will be inserted between prefix and suffix
    artifacts:
      - type   : "asis"
        prefix : "snowplow-spark-enrich-"
        suffix : ".jar"
        binary_paths:
          - "3-enrich/spark-enrich/target/scala-2.11/snowplow-spark-enrich-{{ packages.0.build_version }}.jar"
