---
# --- Variables --- #

repo     : "snowplow-generic"
user_org : "snowplow"

versions:
  scala_stream_collector     : "0.10.0"
  stream_enrich              : "0.11.1"

binary_paths:
  scala_stream_collector     : "2-collectors/scala-stream-collector/target/scala-2.11/snowplow-stream-collector"
  stream_enrich              : "3-enrich/stream-enrich/target/scala-2.11/snowplow-stream-enrich"

# --- Release Manager Config --- #

local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

packages:
  - repo     : "{{ repo }}"
    name     : "snowplow"
    user_org : "{{ user_org }}"
    publish  : true
    override : false
    continue_on_conflict: false
    version  : <%= CMD['echo `cat VERSION` | xargs echo -n'] %>
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>
    build_commands:
      - cd 2-collectors/scala-stream-collector && sbt assembly
      - cd 3-enrich/stream-enrich && sbt assembly
    artifacts:
      - prefix : "snowplow_kinesis_"
        suffix : ""
        type   : "zip"
        binary_paths:
          - "{{ binary_paths.scala_stream_collector }}-{{ versions.scala_stream_collector }}.jar"
          - "{{ binary_paths.stream_enrich }}-{{ versions.stream_enrich }}.jar"

  - repo     : "{{ repo }}"
    name     : "snowplow-scala-stream-collector"
    user_org : "{{ user_org }}"
    publish  : true
    override : false
    continue_on_conflict: true
    version  : "{{ versions.scala_stream_collector }}"
    build_version : "{{ versions.scala_stream_collector }}"
    artifacts:
      - prefix : "snowplow_scala_stream_collector_"
        suffix : ""
        type   : "zip"
        binary_paths:
          - "{{ binary_paths.scala_stream_collector }}-{{ versions.scala_stream_collector }}.jar"

  - repo     : "{{ repo }}"
    name     : "snowplow-stream-enrich"
    user_org : "{{ user_org }}"
    publish  : true
    override : false
    continue_on_conflict: true
    version  : "{{ versions.stream_enrich }}"
    build_version : "{{ versions.stream_enrich }}"
    artifacts:
      - prefix : "snowplow_stream_enrich_"
        suffix : ""
        type   : "zip"
        binary_paths:
          - "{{ binary_paths.stream_enrich }}-{{ versions.stream_enrich }}.jar"

