:targets:
  - :name:     # Insert your own name to identify the database
    :type:     redshift
    :host:     # Insert Redshfit host
    :database: # Insert database name
    :port:     # Insert database port
    :username: # Insert username with relevant credentials to run the below queries
    :password: # Insert user password
:steps:
  - :name: 02-events-enriched
    :queries:
      - :name: 02-01-join-unstructured
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/02-events-enriched/02-01-join-unstructured.sql
  - :name: 03-identity-stitching
    :queries:
      - :name: 03-XX-join-users
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/03-identity-stitching/03-XX-join-users.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-01-basic
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/04-sessions/04-01-basic.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-02-geo
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/04-sessions/04-02-geo.sql
      - :name: 04-03-landing-page
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/04-sessions/04-03-landing-page.sql
      - :name: 04-04-exit-page
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/04-sessions/04-04-exit-page.sql
      - :name: 04-05-source
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/04-sessions/04-05-source.sql
      - :name: 04-06-tech
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/04-sessions/04-06-tech.sql
  - :name: 04-sessions
    :queries:
      - :name: 04-07-move-to-pivot
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/04-sessions/04-07-move-to-pivot.sql
  - :name: 05-visitors
    :queries:
      - :name: 05-01-basic
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/05-visitors/05-01-basic.sql
  - :name: 05-visitors
    :queries:
      - :name: 05-02-landing-page
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/05-visitors/05-02-landing-page.sql
      - :name: 05-03-source
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/05-visitors/05-03-source.sql
  - :name: 05-visitors
    :queries:
      - :name: 05-04-move-to-pivot
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/05-visitors/05-04-move-to-pivot.sql
  - :name: 06-page-views
    :queries:
      - :name: 06-01-page-views
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/06-page-views/06-01-page-views.sql
  - :name: 07-structured-events
    :queries:
      - :name: 07-01-structured-events
        :file: snowplow/5-analytics/redshift-analytics/data-models/sql/full/07-structured-events/07-01-structured-events.sql